# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    build:
      context: ./candidate-management-app-backend # Use an image built from the specified dockerfile in the `polling-app-server` directory.
      dockerfile: Dockerfile
    ports:
      - "8989:8989" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend
    image: muhammadwaqasmbd/candidate-management-app-backend
    volumes:
    - 'myshare:/shared'
        
  # Frontend Service 
  app-client:
    build:
      context: ./candidate-management-app-frontend # Use an image built from the specified dockerfile in the `polling-app-client` directory.
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://localhost:8989/candidatemanagement
    ports:
      - "3000:3000" # Map the exposed port 80 on the container to port 9090 on the host machine
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend  
    image: muhammadwaqasmbd/candidate-management-app-frontend
    volumes:
    - 'myshare:/shared'

volumes:
  myshare:
    driver: local
    
# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend: